name: auto-merge

on:
  pull_request:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{secrets.PERSONAL_PAT}}