name: Pre-Merge Validation

on:
  pull_request:
    branches: [main]

jobs:
  pr-validation:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: 'NPM: build'
        run: 'npm run build'

      - name: 'EsLint: checking lint rules'
        run: 'npm run lint'

      - name: 'NPM: test'
        run: 'npm run test:ci:report'

      - name: Publish Junit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: 'reports/jest-junit.xml'
          check_name: 'Unit test results'
